# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-22 12:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_groupuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkClock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(blank=True, null=True)),
                ('is_enter', models.BooleanField(default=False)),
                ('is_exit', models.BooleanField(default=False)),
                ('last_enter', models.BigIntegerField(blank=True, null=True)),
                ('last_exit', models.BigIntegerField(blank=True, null=True)),
                ('seconds', models.BigIntegerField(blank=True, default=0, null=True)),
                ('guser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bot.groupUser')),
            ],
        ),
    ]
