# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-23 11:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_auto_20171023_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupuser',
            name='fio',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
