# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-21 17:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='botUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.BigIntegerField()),
                ('step', models.CharField(blank=True, max_length=50, null=True)),
                ('username', models.CharField(default='Empty', max_length=120)),
                ('fio', models.CharField(default='Empty', max_length=120)),
                ('date_in', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Telegram User',
                'verbose_name': 'Telegram User',
            },
        ),
    ]
