# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-28 19:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0006_auto_20171023_1435'),
    ]

    operations = [
        migrations.CreateModel(
            name='group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.BigIntegerField()),
                ('group_name', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Telegram Group',
                'verbose_name_plural': 'Telegram Group',
            },
        ),
        migrations.DeleteModel(
            name='botUser',
        ),
        migrations.RenameField(
            model_name='groupuser',
            old_name='gchat_id',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='workclock',
            old_name='guser',
            new_name='user',
        ),
        migrations.AddField(
            model_name='groupuser',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bot.group'),
        ),
    ]
