# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 08:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0009_journal'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='journal',
            options={'verbose_name': 'Journal', 'verbose_name_plural': 'Journal'},
        ),
        migrations.AlterModelOptions(
            name='lightning',
            options={'verbose_name': 'Lightning', 'verbose_name_plural': 'Lightning'},
        ),
    ]
