# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 15:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0010_auto_20171030_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='date_in',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='journal',
            name='date_out',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
