# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-03 05:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0011_auto_20171030_1817'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupuser',
            name='start_hour',
            field=models.IntegerField(default=9),
        ),
        migrations.AddField(
            model_name='groupuser',
            name='start_minute',
            field=models.IntegerField(default=0),
        ),
    ]
