# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-06 07:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0012_auto_20171103_0859'),
    ]

    operations = [
        migrations.CreateModel(
            name='Otpros',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_in', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bot.groupUser')),
            ],
            options={
                'verbose_name': 'Otpros',
                'verbose_name_plural': 'Otproses',
            },
        ),
    ]
