# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-26 09:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0013_otpros'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_event', models.DateTimeField(blank=True, null=True)),
                ('eventMessage', models.CharField(blank=True, max_length=220, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bot.groupUser')),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Event',
            },
        ),
        migrations.CreateModel(
            name='EventStage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.BigIntegerField()),
                ('messageState', models.BigIntegerField()),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bot.Event')),
            ],
            options={
                'verbose_name': 'EventStage',
                'verbose_name_plural': 'EventStage',
            },
        ),
        migrations.AddField(
            model_name='workclock',
            name='currentLocation',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
