# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-16 10:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0014_auto_20171126_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupuser',
            name='isOtpusk',
            field=models.BooleanField(default=False),
        ),
    ]
