# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-16 13:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0015_groupuser_isotpusk'),
    ]

    operations = [
        migrations.AddField(
            model_name='workclock',
            name='light_setted',
            field=models.BooleanField(default=False),
        ),
    ]
